import localFont from 'next/font/local';
import "./globals.css";
import Header from "@/components/header";

const SFMono=localFont({
  src: '../fonts/SFMono-Regular.woff2',
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={SFMono.className}>
      <body><Header/>{children}</body>
    </html>
  );
}
